pipeline {
    agent { label 'windows' }

    environment {
        DEPLOY_DIR = "P:/Jenkinss"  // Still defined, but unused
    }

    stages {
        stage('Prepare Deploy Folder') {
            steps {
                bat 'if not exist P:\\Jenkinss mkdir P:\\Jenkinss'
                echo "Deploy folder prepared"
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/rajuneduri/jenkins.git'
                echo "Successfully pulled the code"
            }
        }

        stage('Build with Maven') {
            steps {
                dir('jenkinstesting') {
                    bat 'mvn clean install'
                }
                echo "Successfully created JAR"
            }
        }

stage('Run Application in Background') {
            steps {
                script {
                    def jarPath = "${env.WORKSPACE}\\jenkinstesting\\target\\jenkinstesting-0.0.1-SNAPSHOT.jar"

                    echo "Running application from: ${jarPath}"

                    // Launch the application in the background (no new window, persistent)
                    bat "start /b java -jar \"${jarPath}\""
                }
            }
        }


//         stage('Run Application') {
//             steps {
//                 script {
//                     def jarFile = bat(
//                         script: 'for /f %%i in (\'dir /b jenkinstesting\\target\\*.jar\') do @echo %%i',
//                         returnStdout: true
//                     ).trim()
// echo "Found JAR file: ${jarFile}"
//                     echo "Running ${jarFile} from workspace"
//
//                       def jarPath = "jenkinstesting\\target\\${jarFile}"
//                                 echo "Running application using JAR: ${jarPath}"
//
//                     // Properly run the jar
//                     bat "start \"SpringApp\" cmd /c \"java -jar ${jarPath}\""
//                 }
//             }
//         }



    }
    

    post {
       success {
               echo 'Build and Deployment Successful!'

               emailext (
                   to: 'rajuneduri2255@gmail.com',
                   subject: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                   body: """<p>Good news!</p>
                            <p>The build and deployment of job <b>${env.JOB_NAME}</b> #${env.BUILD_NUMBER} was successful.</p>
                            <p>Check details at: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>""",
                   mimeType: 'text/html'
               )
           }
       failure {
               echo 'Pipeline Failed!'

               emailext (
                   to: 'rajuneduri2255@gmail.com',
                   subject: "FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                   body: """<p>Unfortunately, the job <b>${env.JOB_NAME}</b> #${env.BUILD_NUMBER} has failed.</p>
                            <p>Please review the build at: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>""",
                   mimeType: 'text/html'
               )
           }
    }
}
